spring.application.name=wexp

security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
security.jwt.expiration-time=86400000

steam.api.base-url=https://api.steampowered.com
steam.store.base-url=https://store.steampowered.com
steam.images.base-url=https://cdn.akamai.steamstatic.com/steam/apps
steam.capsule-image-base-url=https://shared.akamai.steamstatic.com/store_item_assets/steam/apps
steam.api.key=CC4315CE3B0CCA9D9F1B83C46253474C

thecatapi.api.base-url=https://api.thecatapi.com

spring.datasource.url=jdbc:postgresql://localhost:5432/wexp
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true